### ISSUE TITLE
Outside mail server

### ISSUE THREAD

**Issue by egavard** [cozy-labs/cozy-docker#12]
Hi,

First of all, thank you for your job! 
I'm looking to find a way in order to configure the mail server used by the cozy cloud container.
Did someone ever do this ? 
Is there a roadmap of next features where I can check if this question has already beed answered ?

**Comment by clochix** [comment]
Hi @dy0nysos,

Thanks for your encouragements ☺

We plan to allow to use one of the accounts defined in the Email application to send messages from cozy, so this will be a way to address your issue. But this is not on top of our priorities, and it won't probably happen before months.

But allowing to use an external SMTP server shouldn't be too hard, basically I think it's just changing the mail transport used [here](https://github.com/cozy/cozy-data-system/blob/master/server/controllers/mails.coffee), so if you're interested in some hacking, we can help you perform this patch ;-)

**Comment by egavard** [comment]
Hi @clochix ,

I'll probably try to add this improvement on my side and won't hesitate to pull it on this repo.

Thanks for your answer :)

**Comment by frankrousseau** [comment]
@dy0nysos can we close this issue?

**Comment by egavard** [comment]
@frankrousseau I do it right now.
