### ISSUE TITLE
Certificate common name

### ISSUE THREAD

**Issue by laem** [cozy-labs/cozy-docker#4]
https://github.com/cozy-labs/cozy-docker/blob/master/Dockerfile#L103
This line sets the certificate's common name to `localhost`, which results in a incorrect certificate, e.g. when setting DAVDroid (through CADroid) to sync contacts. 
Is there a way to cleanly deal with this ?
The container has been working perfectly, this problem aside.

**Comment by frankrousseau** [comment]
Thank you laem for reporting. I think you will have to modify the Dockerfile by hand.
@Kloadut any idea?

**Comment by nledez** [comment]
I think about it. But I did'nt found a way to pass parameters to the build command.

And I don't know if it be a good practice.

May be the good way is to have a post installation in the instance to replace the image one.

Another way (or thing to do) is to remove the CN from certificate.
![image](https://cloud.githubusercontent.com/assets/247138/6978504/77b81882-d9d4-11e4-88df-9529c403c8c2.png)

**Comment by laem** [comment]
OK. That's how I've fixed it meanwhile without running the dockerfile again. Not ideal, but it works. 

```
sudo docker exec -i -t RUNNING_DOCKER_NAME bash

sudo openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/cozy/server.key -out /etc/cozy/server.crt -days 365 -subj '/CN=DOMAIN_NAME'
```

**Comment by Kloadut** [comment]
@laem This is the right way to do it for now.

I will integrate a small configuration to the docker repository, so that one can choose his certificate, or at least his domain name.

**Comment by Kloadut** [comment]
Done as of https://github.com/cozy-labs/cozy-docker/commit/8dbf892d82b26942c26a5932bd0717ce979daf36

Now the security tokens are generated at the container initialization.

**Comment by Refhi** [comment]
Indeed they are, but they still default to localhost. Is it expected ?

**Comment by Kloadut** [comment]
It is expected, you can set your domain name by launching your newly created cozy container with the option `-e DOMAIN=mydomain.org`

**Comment by Refhi** [comment]
cool, thanks a lot, I'll update the wiki.
