### ISSUE TITLE
login screen redirects to 443 by default

### ISSUE THREAD

**Issue by arthurlutz** [cozy-labs/cozy-docker#5]
Hi,

I'm running my cozy-docker on a host that already has some stuff on port 80 and 443. So when running it I did 

```
docker run -d -p 9880:80 -p 9443:443 cozy
```

setting up on host:9880 seems to work, it then tries to redirecto host:443 and not host:9443. Is there a way to configure cozy via some --env variables sent through docker ? 

I can manually go to host:9443 to get it working this is a "would be nice" feature request.

**Comment by frankrousseau** [comment]
@Kloadut Any idea?

**Comment by nledez** [comment]
It may be come from:
https://github.com/cozy-labs/cozy-docker/blob/master/nginx/cozy-ssl#L35

And if redirect not made by nginx, it may come from proxy/home.

But why do you want run Cozy on "exotic" port @arthurlutz?

On Cozy we have made the choice of standards ports to pass easily "dummy/enterprise" firewalls.

**Comment by arthurlutz** [comment]
@nledez this is more of a temporary setting while setting up and trying out cozy on a machine that already has stuff configured on port 443. You could tell me : setup your apache to proxy to your 9443 and be done with it. It's just a UX use case of users trying it with an exotic port and then adopting it and putting it on a public url with the standard port.

**Comment by Kloadut** [comment]
@arthurlutz That's right, there is no way to redirect properly from inside the container.

You can run your container with the `-e DISABLE_SSL=true` option, so that you you can handle SSL certificates and redirections from outside, via a proxy. But this is the only way to do it right.
